### ISSUE TITLE
Any more cheat sheets in the pipeline?

### ISSUE THREAD

**Issue by luzpaz** [EvokeMadness/FreeCAD-Cheat-Sheets#1]
Love the work you've done. Any plans to do more?

**Comment by EvokeMadness** [comment]
Hi,

Thanks. I am currently working on a cheat sheet for the Part Design workbench. I think going from the Sketcher workbench to Part Design is common practice for most users looking to get into CAD and solid modeling. However, this part is tricky due to it being example heavy. And choosing information that is both useful and agnostic must be done with careful thought. If you're interested in another workbench please let me know, and I'd be happy to hear how you found the Sketcher cheat sheet helpful, and if you've shared it.

**Comment by EvokeMadness** [comment]
Sorry for the lack of updates. I've been working on achieving my certifications in CAD.
